Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\decorators.py", line 20, in wrap
    resp = function(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\views.py", line 234, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\views.py", line 77, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\views.py", line 207, in dispatch
    return super(CloseableSignupMixin, self).dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\views.py", line 104, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\forms\forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\forms\forms.py", line 196, in errors
    self.full_clean()
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\forms\forms.py", line 433, in full_clean
    self._clean_fields()
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\forms\forms.py", line 448, in _clean_fields
    value = getattr(self, "clean_%s" % name)()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\forms.py", line 357, in clean_email
    value = get_adapter().clean_email(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\users\adapter.py", line 13, in clean_email
    if email.split("@")[1] in settings.RESTRICTED_DOMAINS_FOR_USER_REGISTRATION:
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\conf\__init__.py", line 104, in __getattr__
    val = getattr(_wrapped, name)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Settings' object has no attribute 'RESTRICTED_DOMAINS_FOR_USER_REGISTRATION'
"POST /accounts/signup/ HTTP/1.1" 500 149059
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\decorators.py", line 20, in wrap
    resp = function(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\views.py", line 234, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\views.py", line 77, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\views.py", line 207, in dispatch
    return super(CloseableSignupMixin, self).dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\views.py", line 104, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\forms\forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\forms\forms.py", line 196, in errors
    self.full_clean()
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\forms\forms.py", line 433, in full_clean
    self._clean_fields()
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\forms\forms.py", line 448, in _clean_fields
    value = getattr(self, "clean_%s" % name)()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\forms.py", line 357, in clean_email
    value = get_adapter().clean_email(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\users\adapter.py", line 13, in clean_email
    if email.split("@")[1] in settings.RESTRICTED_DOMAINS_FOR_USER_REGISTRATION:
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\conf\__init__.py", line 104, in __getattr__
    val = getattr(_wrapped, name)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Settings' object has no attribute 'RESTRICTED_DOMAINS_FOR_USER_REGISTRATION'
"POST /accounts/signup/ HTTP/1.1" 500 149059
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\decorators.py", line 20, in wrap
    resp = function(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\views.py", line 234, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\views.py", line 77, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\views.py", line 207, in dispatch
    return super(CloseableSignupMixin, self).dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\views.py", line 104, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\forms\forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\forms\forms.py", line 196, in errors
    self.full_clean()
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\forms\forms.py", line 433, in full_clean
    self._clean_fields()
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\forms\forms.py", line 448, in _clean_fields
    value = getattr(self, "clean_%s" % name)()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\allauth\account\forms.py", line 357, in clean_email
    value = get_adapter().clean_email(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\users\adapter.py", line 13, in clean_email
    if email.split("@")[1] in settings.RESTRICTED_DOMAINS_FOR_USER_REGISTRATION:
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\MediaUploadX\venv\Lib\site-packages\django\conf\__init__.py", line 104, in __getattr__
    val = getattr(_wrapped, name)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Settings' object has no attribute 'RESTRICTED_DOMAINS_FOR_USER_REGISTRATION'
"POST /accounts/signup/ HTTP/1.1" 500 149059
